plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
sass:
  sass_dir: assets/styles
social:
  name: Ravi Pradhan
  links:
    - https://twitter.com/raviipx
    - https://github.com/rav-pradhan
    - https://www.linkedin.com/in/ravipradhan/
    - https://toot.wales/@ravi
logo: /assets/images/logo.png
twitter:
  username: raviipx
  creator: raviipx
  card: summary
author: Ravi Pradhan
url: https://ravii.dev
tagline: The personal website for Ravi Pradhan, a generalist software engineer, technologist, and inclusive designer based in Cardiff, Wales.
locale: en_GB

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/rp-logo.jpg

markdown: kramdown

